### ISSUE TITLE
Windows icon is bugged

### ISSUE THREAD

**Issue by ThomasDNguyen** [Kudostoy0u/pwsh10k#2]
I'm currently running Windows Terminal + PowerShell Preview 
I have followed the readme file + handled the script execution policy and got everything up and running. However, there seems to be a problem with the windows icon glyph because it doesn't seem to be displaying properly
[https://i.imgur.com/M7Njqdh.png](url)
Also, the battery icon is replaced with a small sprouting tree (although, I assume this is more likely a new update?)
[https://i.imgur.com/IbpZ7Nc.png](url)

**Comment by ThomasDNguyen** [comment]
Update:
So apparently it isn't bugged it just has bad scaling when font size is set to anything below 16. As long as the font size is >= 16 the icon shows as intended.
Is there a way to get it working in a smaller font size?

**Comment by Kudostoy0u** [comment]
I have no control over the Windows icon from Font Awesome and thus cannot troubleshoot any bugs with the appearance (I think it is because there aren't enough pixels to show the gaps that are part of the icon)

As for the battery icon being replaced with a small sprouting tree, I cannot replicate this issue, everything is working fine on my end. Maybe try to update `oh-my-posh` to the newest version, reinstall the fonts, and reinstall the theme.?

![image](https://user-images.githubusercontent.com/69732000/121726084-addd9680-caaf-11eb-9ef5-68ba07b6f4c2.png)

**Comment by ThomasDNguyen** [comment]
Yeah, I've made changes to the fonts and icons and everything works besides the windows icon unable to display properly when scaled down. It's just a matter of aesthetics and I understand you have no control over it. Thanks for replying anyway.

**Comment by Kudostoy0u** [comment]
> Yeah, I've made changes to the fonts and icons and everything works besides the windows icon unable to display properly when scaled down. It's just a matter of aesthetics and I understand you have no control over it. Thanks for replying anyway.

You could always commit the changes you made to this Github repository 😉
